import React from 'react';

function Proposals() {
  const dataProposals = [
    { title: "Investir no mínimo 85% dos recursos destinados à mobilidade nos modos ativos e coletivos de transporte, bem como na segurança no trânsito, os próximos 4 (quatro) anos.", text: "Diante da vulnerabilidade de Recife, identificada pelo Painel Intergovernamental sobre Mudanças Climáticas (IPCC) da ONU como a capital brasileira mais exposta aos efeitos das mudanças climáticas, o município deve adotar medidas urgentes para prevenir tragédias como as enchentes no Rio Grande do Sul. Essas políticas devem incluir o fortalecimento da infraestrutura de mobilidade urbana, priorizando modos de transporte sustentáveis e seguros, e garantir a adaptação das vias, ciclovias, calçadas, e sistemas de transporte coletivo às novas condições climáticas, de modo a proteger a população e aumentar a resiliência da cidade frente a eventos extremos. A Pesquisa Origem Destino da Prefeitura do Recife via Instituto Pelópidas Silveira mostrou que, na divisão modal, mais de 85% da população utiliza os modos de transportes sustentáveis (o caminhar, a bicicleta e o transporte coletivo) para o trabalho ou estudo. Apesar disso, o investimento em vias para automóveis no Recife é 5 vezes maior que nos demais modos de transporte. Se somos 85% dos deslocamentos, nada mais justo termos 85% do financiamento da mobilidade. Para atingir essa meta, propõe-se a alocação de pelo menos 85% dos recursos hoje destinado ao asfaltamento e recapeamento nas rubricas de consolidação e manutenção do viário; a destinação de pelo menos 25% dos recursos advindos da fiscalização do trânsito; e, pelo menos 15% dos recursos auferidos por meio da contrapartida financeira da Outorga Onerosa do Direito de Construir (conforme Plano Diretor) em estrutura para os modos sustentáveis. Além disso, são possíveis outras ações de corte de financiamento ao automóvel, como aluguel de carros oficiais e gasolina de vários órgãos, migrando para os modos sustentáveis de transporte, além da arrecadação por meio da taxação do uso do motorizado individual para o financiamento da mobilidade sustentável, à exemplo da expansão da zona azul e da taxação dos transportes por aplicativo." },
    { title: "Cumprir o estabelecido na Política de Mobilidade Urbana do Recife, lei municipal número 18.887/2021 , em seu artigo 34, que estabelece como velocidade máxima nas vias arteriais como 50km/h e ampliar a fiscalização desses limites nesses pontos e reestabelecer a fiscalização eletrônica 24h por dia no primeiro mês de 2025.", text: "A proposta inclui a reativação dos sistemas de fiscalização existentes, a instalação de novos equipamentos em pontos estratégicos com alto índice de acidentes, e a expansão da cobertura para áreas atualmente desassistidas. Além disso, será promovida ações com a redução de velocidades, com foco especial em vias principais da cidade. Como ações obrigatórias à uma política de redução de mortes tem-se a redução das velocidades máximas das vias arteriais para 50km/h (como orienta desde 2011 a Organização Mundial de Saúde), com a reativação e ampliação da fiscalização eletrônica no trânsito do Recife é urgente e necessária, pois os radares de velocidade na cidade estão desativados há mais de um ano devido a atrasos em processos de licitação (PCR 2023). Além da reativação, faz-se necessária que essa fiscalização aconteça em tempo contínuo, conforme manda a legislação. As 10 vias com mais violência (70 km dos 2400 totais) concentram 30% das vítimas, as 75 mais violentas (100 km dos 2.400 totais) concentram 50%, e as 200 mais violentas concentram 80%. Diante desses dados apresentados fica evidente que resolver buscar uma solução para os altos índices de sinistros de trânsito no município de Recife não é uma missão impossível como se imagina. Essa inatividade compromete a segurança viária e deixa a população vulnerável. Estudos demonstram que a fiscalização eletrônica, especialmente a redução de velocidade, é uma das medidas mais eficazes para reduzir mortes no trânsito. Com a reativação dos radares e a instalação de novos equipamentos, será possível retomar o controle sobre o comportamento dos motoristas, especialmente nas vias principais, onde o excesso de velocidade é uma das principais causas de vítimas fatais. Assim, a cidade poderá reduzir significativamente o número de mortes e lesões no trânsito, protegendo a vida de seus cidadãos e promovendo um ambiente urbano mais seguro e sustentável." },
    { title: "Implementar pelo menos 70 km de ciclovias nas 10 avenidas mais perigosas da cidade nos primeiros 2 anos de gestão, finalizar os demais 180 km e converter as ciclofaixas existentes em ciclovias até o fim de 2028.", text: "Lançado em 2014 pelo Governo do Estado de Pernambuco em parceria com as prefeituras da Região Metropolitana do Recife e participação da sociedade civil, o Plano Diretor Cicloviário da RMR prevê a construção de 250km de ciclovias na capital. No entanto, nesses últimos 4 anos, com poucas exceções, foram implantadas somente ciclofaixas e ciclorrotas e nas vias paralelas aos principais corredores, onde deveria-se ter segurança para todas as pessoas, inclusive ciclistas. A Associação Metropolitana de Ciclistas do Recife realizou um estudo priorizando as vias mais perigosas da cidade, que coincidem com cerca de 70 km das vias arteriais, exatamente pelas suas características de permissão de alta velocidade e que, portanto, devem ser prioridade para a segurança no trânsito de todas as pessoas todas pessoas. Essas estruturas irão ajudar na recuperação econômica, além de fazer do Recife uma cidade mais segura, mais rica, mais saudável e menos poluída. São as 10 avenidas mais perigosas, à exceção da Agamenon Magalhães, que já tem estrutura implantada nas avenidas: Norte Miguel Arraes de Alencar, Caxangá, Dr. José Rufino e São Miguel, Beberibe e Estrada Velha de Água Fria, Marechal Mascarenhas de Moraes, Ponte Paulo Guerra, Herculano Bandeira, Engenheiro Domingos Ferreira e Visconde de Jequitinhonha, Engenheiro Abdias de Carvalho, Sport Clube do Recife e Paisandu, Dezessete de Agosto, Apipucos e Manuel de Medeiros" },
    { title: "Colocar em regime de urgência a elaboração dos cadernos técnicos, planos de metas e implementação da Política Municipal de Mobilidade Urbana e suas Políticas Setoriais para o primeiro trimestre de 2025, da forma como foram aprovadas na Câmara Municipal da Cidade do Recife.", text: "Aprovada em 2021, a demora na implementação da Política Municipal de Mobilidade Urbana impede Recife de adotar medidas essenciais para reduzir as mortes no trânsito, melhorar a qualidade de vida dos cidadãos e combater a poluição, que contribui para o agravamento do colapso climático. A criação dos cadernos técnicos é crucial para padronizar e executar intervenções urbanas de forma eficiente, assegurando que as obras e ajustes necessários nas infraestruturas de transporte sejam realizados de maneira coesa e planejada. A urgência na implementação dessas políticas é vital para que Recife esteja mais bem preparado para enfrentar os desafios de mobilidade e assegurar o direito à cidade para todos os seus habitantes." },
    { title: "Fazer ampliação e manutenção dos passeios públicos, bem como, dobrar as metas do Projeto Calçada Legal, de maneira progressiva ao longo do próximo mandato, priorizando a execução nas vias por onde passam o transporte coletivo.", text: "As nossas calçadas são o principal meio de acesso à cidade, inclusive para 16% da nossa população que vai às escolas apenas pela caminhada ou pelas mais de 60% das pessoas que usam o transporte coletivo e o acessam por meio das calçadas. No entanto, apesar da manutenção das pistas serem de responsabilidade do poder público municipal, segundo a disposto no Código de Trânsito Brasileiro, que define a calçada como parte da via, sendo assim um bem público. A política atual de novas calçadas, como o Calçada Legal, é um ponto positivo nesses últimos anos e realmente tem atingido as principais vias e corredores de transporte da cidade, precisando ser ampliado e acelerado. E para que não seja um projeto transitório de governo, precisa se transformar em política pública municipal. Assumido esse compromisso, deve-se ampliar a reestruturação das calçadas e travessias de pedestres priorizando as vias estruturantes e conectoras do Recife, de acordo com o disposto no Relatório A Mobilidade do Recife Hoje (ICPS), fornecendo pavimentação, iluminação, sinalização e arborização adequadas, garantindo também a acessibilidade e a travessia segura de pessoas com deficiência e mobilidade reduzida." },
    { title: "Em todas as vias por onde passam pelo menos 40 ônibus por hora, em algum momento do dia, devem conter faixa exclusiva de ônibus até 2028.", text: "O Recife possui o maior tempo de espera pelo transporte coletivo entre as 10 maiores regiões metropolitanas, mesmo sendo o principal meio de locomoção de 60% de quem estuda e de 70% de quem trabalha. Além disso, é a sétima cidade do mundo que mais perde tempo nos deslocamentos (Moovit, 2020). No entanto, apesar de transitar em cerca de 650 km de vias da cidade, apenas 67 km (10,3%) possuem alguma priorização para o transporte coletivo. Apenas 5,4 km foram implantados nos últimos 4 anos, estando muitos trechos ainda desconectados. As faixas exclusivas de ônibus trazem comprovadamente ganhos consideráveis no tempo de viagem dos usuários e das usuárias do sistema, além de reduzir os custos gerais de operação e a emissão de poluentes. Alguns estudos apontam que as faixas devem operar quando em algum momento do dia, no intervalo de uma hora, passam entre 25 e 40 ônibus (Associação Nacional das Empresas de Transportes Urbanos, 2002). Portanto, adotamos a métrica mais flexível, tendo esperança de que metas mais ousadas possam trazer conforto, confiabilidade e segurança para usuários e usuárias do transporte coletivo do Recife." },
  ]
  return (
    <main>
      <div className="home-proposals">
        <h1>Nossas Propostas</h1>
        <div className="proposals-card">
          {dataProposals.map((proposal, index) => {
            return (<h4><a href={`./propostas/${index}`}>{proposal.title}</a></h4>)
          })}
        </div>
      </div>
    </main>
  );
}

export default Proposals;